# Generated by Django 5.2.1 on 2025-06-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_author_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(null=True, upload_to='media/files'),
        ),
    ]
